spring:
  jpa:
    hibernate:
      ddl-auto: none
      order_inserts: true
      order_updatest: true
      jdbc:
        batch_size: 4
    generate-ddl: false
    show-sql: true
  datasource:
    url: jdbc:mysql://microservice-mysql:3306/main?serverTimezone=Asia/Jerusalem
    username: root
    password: root
    data: classpath:schema.sql
    initialization-mode: always
jwt:
  secret: javainuse
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://microservice-registry:8761/eureka/