spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
      order_inserts: true
      order_updatest: true
      jdbc:
        batch_size: 4
    generate-ddl: true
    show-sql: true
  datasource:
    url: jdbc:mysql://microservice-mysql:3306/test5?serverTimezone=Asia/Jerusalem
    username: root
    password: root
jwt:
  secret: javainuse
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://microservice-registry:8761/eureka/